<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-styles-repository',
	'deps' => [
		'elementor-v2-editor-elements',
		'elementor-v2-editor-v1-adapters',
<<<<<<< HEAD
		'elementor-v2-utils',
=======
>>>>>>> fa623e74ce55ca1a48265d395a80daf0b504f244
		'react',
	],
];
